### ISSUE TITLE
Download favorite videos

### ISSUE THREAD

**Issue by tmk907** [tmk907/MyTikTokBackup#1]
Parse `user_data.json` file and download favorite videos. 
Rename existing 'favorite' to 'liked'

**Comment by tmk907** [comment]
> although i added it, it does not find all of them, 
(my total is 370, once it finds 29, once 38, it just changes) .
what is worse is that the download button does nothing, even for this 29 or whatsoever 38 ones. (error in download tab)

> _Originally posted by @sabaak95 in https://github.com/tmk907/TikTokDownloader/issues/9#issuecomment-1003686110_


I tested it on my 11 bookmarks and it worked fine. I noticed that sometimes server returns response that requires solving captcha. It might be reason why only ~30 videos are found. I dont know yet why you could download them (errors in download tab).

**Comment by tmk907** [comment]
I used different method to get urls to download and added some delay between making requests. 
@sabaak95 You can try version 1.1.7 when it will be available in Store.

**Comment by sabaak95** [comment]
This seems not to be working yet. 
Can you tell me how can to convert videos in this format:
https://www.tiktokv.com/share/video/7046969412980706561
to something which can be opened/downloaded? I have difficulty finding this in ur code

**Comment by tmk907** [comment]
Version 1.1.7 is still in certification process. 
This method https://github.com/tmk907/MyTikTokBackup/blob/9175a284720c88e2b523f90fd2c8b184992f37f1/MyTikTokBackup.Desktop/MyTikTokBackup.Desktop/ViewModels/UserDataViewModel.cs#L175 finds url in format @user/videoid. It uses oembed api.

**Comment by sabaak95** [comment]
yeah it is weird sometimes the tiktokv/share urls redirect to an actual
working video but sometimes it just returns a json response I guess (or
some info and numbers I am not sure what they are)

so I guess I need to wait for the app to get verified

**Comment by sabaak95** [comment]
Hi,
Isnt this getting uploaded? it has been a week

**Comment by tmk907** [comment]
Yesterday I resubmitted application, because it was still stuck in certification process. And 1.1.7 is finally available.

**Comment by tmk907** [comment]
Meantime TikTok changed something on backend and requires to add User-Agent header to request. I have to update app again.

**Comment by sabaak95** [comment]
Oh I see it is updated now.
I reuploaded the user json and now it finds all the URLs. but when I press
download, nothing happens ( probably as u said there should be a problem
with the headers and requests. )
so yeah thank u for taking the time. I am looking forward for this to
finally work :)

**Comment by tmk907** [comment]
Version 1.1.8 is available

**Comment by tmk907** [comment]
Were you able to download the bookmarked videos?

**Comment by sabaak95** [comment]
Hello,
Yes!! but there is only one problem. I had 387 videos, only 368 downloads
though.
Is it probably related to the fact that they have private pages/ maybe
another reason?
Is it going to fix if I log in to the mytiktokbackup app? Or the
downloading is independent module?

Best,
Saba

**Comment by sabaak95** [comment]
now it is only 176 of them downloaded

**Comment by tmk907** [comment]
> Is it probably related to the fact that they have private pages/ maybe
another reason?

Yes, private, deleted or maybe account was deleted. You also won't be able to watch this video in browser.

> Is it going to fix if I log in to the mytiktokbackup app?

It doesn't matter.

> now it is only 176 of them downloaded

"favorite videos to download" is number of videos where app could parse webpage and find url to download file. One of the reasons why it's less than "found urls" is that TikTok detected unusual traffic and returned captcha instead of normal page. 
I will add function to check which videos were downloaded. This may require you to run the download multiple times, but eventually all the videos will download.

**Comment by tmk907** [comment]
New version is available. I had to change app name, it's now listed in Store as MyTTBackup.

**Comment by sabaak95** [comment]
I cannot find it unfortunately

**Comment by tmk907** [comment]
The application has been removed from the Store, but you can install the msix package instead [https://github.com/tmk907/MyTikTokBackup/releases](https://github.com/tmk907/MyTikTokBackup/releases)
