### ISSUE TITLE
Create a NuGet Package for this lib

### ISSUE THREAD

**Issue by meredithdawson** [tmk907/MyTikTokBackup#2]
First thank you for that great package.
Would be nice if you could create a NuGet package for it. 
That would increase the visibility of that package and it would be very easy to update.

**Comment by tmk907** [comment]
I'm not sure I understand what you mean. MyTikTokBackup is Windows application, not library. I think it doesn make sense of making nuget package with part of application.

**Comment by meredithdawson** [comment]
Sorry that was my mistake. I have not looked at the project intensively enough.
