### ISSUE TITLE
Add support for .NET Standard and Xamarin

### ISSUE THREAD

**Issue by meredithdawson** [tmk907/MyTikTokBackup#3]
Support for .NET Standard and Xamarin Android would make the lib useable crossplatform

**Comment by tmk907** [comment]
This app relies on Webview2, its component available only in Windows 10. It's not possible to port MyTikTokBackup to Android.

**Comment by meredithdawson** [comment]
Oh, I see. Does the project use scraping technologies to download videos from tiktok?

**Comment by tmk907** [comment]
App doesn't parse html, but webview executes javascript that reads global variable that stores app state, including list of videos. Plus webview intercepts requests received from servers to get list of videos and cookies.
