### ISSUE TITLE
Install Certificate No Longer Valid

### ISSUE THREAD

**Issue by Hi-ImKyle** [tmk907/MyTikTokBackup#5]
Just tried installing the msix, complained about the certificate, I checked the cert and it was valid up to the 8th of September.

**Comment by tmk907** [comment]
I created new certificate and released new version [https://github.com/tmk907/MyTikTokBackup/releases/tag/v1.1.13](https://github.com/tmk907/MyTikTokBackup/releases/tag/v1.1.13)
