### ISSUE TITLE
Unable to download photo posts

### ISSUE THREAD

**Issue by antpernas** [tmk907/MyTikTokBackup#7]
Love this code!! It's very useful, but I believe it is unable to download photo posts. Would love if this is possible :D Thanks!!

**Comment by tmk907** [comment]
I finally found the time and motivation to do it. Now it's possible to download photo posts. However, they cannot be viewed in the app for now.
[Release 1.1.15](https://github.com/tmk907/MyTikTokBackup/releases/tag/v1.1.15)
